#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:
  application:
    name: saltyfish-server

  profiles:
    active: local

  main:
    allow-circular-references: true ${symbol_pound} 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true
  ${symbol_pound} Servlet 配置
  servlet:
    ${symbol_pound} 文件上传相关配置项
    multipart:
      max-file-size: 16MB ${symbol_pound} 单个文件大小
      max-request-size: 32MB ${symbol_pound} 设置总上传的文件大小
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER ${symbol_pound} 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类

  ${symbol_pound} Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true ${symbol_pound} 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false ${symbol_pound} 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true ${symbol_pound} 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false ${symbol_pound} 允许序列化无属性的 Bean

  ${symbol_pound} Cache 配置项
  cache:
    type: REDIS
    redis:
      time-to-live: 1h ${symbol_pound} 设置过期时间为 1 小时

${symbol_pound} MyBatis Plus 的配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true ${symbol_pound} 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: NONE ${symbol_pound} “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
${symbol_pound}      id-type: AUTO ${symbol_pound} 自增 ID，适合 MySQL 等直接自增的数据库
${symbol_pound}      id-type: INPUT ${symbol_pound} 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
${symbol_pound}      id-type: ASSIGN_ID ${symbol_pound} 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      logic-delete-value: 1 ${symbol_pound} 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 ${symbol_pound} 逻辑未删除值(默认为 0)
  type-aliases-package: ${groupId}.**.domain
  mapper-locations: classpath*:/mapper/*Mapper.xml

--- ${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound} 相关配置 ${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}${symbol_pound}

saltyfish:
  info:
    version: ${version}
    base-package: ${groupId}
  web:
    admin-ui:
      url: www.baidu.com ${symbol_pound} Admin 管理后台 UI 的地址
  security:
    permit-all_urls:
      - /admin-ui/** ${symbol_pound} /resources/admin-ui 目录下的静态资源
  swagger:
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: ${symbol_dollar}{saltyfish.info.version}
    base-package: ${symbol_dollar}{saltyfish.info.base-package}
  captcha:
    timeout: 5m
    width: 160
    height: 60
  codegen:
    base-package: ${symbol_dollar}{saltyfish.info.base-package}
    db-schemas: ${symbol_dollar}{spring.datasource.dynamic.datasource.master.name}
  error-code: ${symbol_pound} 错误码相关配置项
    constants-class-list:
      - ${groupId}.infra.enums.ErrorCodeConstants
      - ${groupId}.member.enums.ErrorCodeConstants
      - ${groupId}.system.enums.ErrorCodeConstants
  tenant: ${symbol_pound} 多租户相关配置项
    enable: true
    ignore-urls:
      - /web-api/system/tenant/get-id-by-name ${symbol_pound} 基于名字获取租户，不许带租户编号
      - /web-api/system/captcha/get-image ${symbol_pound} 获取图片验证码，和租户无关
      - /web-api/system/captcha/get ${symbol_pound} 获取图片验证码，和租户无关
      - /web-api/system/captcha/check ${symbol_pound} 获取图片验证码，和租户无关
      - /web-api/infra/file/*/get/** ${symbol_pound} 获取图片，和租户无关
      - /web-api/system/sms/callback/* ${symbol_pound} 短信回调接口，无法带上租户编号
      - /app-api/pay/order/notify/* ${symbol_pound} 支付回调通知，不携带租户编号
      - /jmreport/*
    ignore-tables:
      - system_tenant
      - system_tenant_package
      - system_dict_data
      - system_dict_type
      - system_error_code
      - system_menu
      - system_sms_channel
      - system_sms_template
      - system_sms_log
      - system_sensitive_word
      - system_oauth2_client
      - infra_codegen_column
      - infra_codegen_table
      - infra_test_demo
      - infra_config
      - infra_file_config
      - infra_file
      - infra_file_content
      - infra_job
      - infra_job_log
      - infra_job_log
      - infra_data_source_config
      - jimu_dict
      - jimu_dict_item
      - jimu_report
      - jimu_report_data_source
      - jimu_report_db
      - jimu_report_db_field
      - jimu_report_db_param
      - jimu_report_link
      - jimu_report_map
      - jimu_report_share
      - rep_demo_dxtj
      - rep_demo_employee
      - rep_demo_gongsi
      - rep_demo_jianpiao
      - tmp_report_data_1
      - tmp_report_data_income
  sms-code: ${symbol_pound} 短信验证码相关的配置项
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 9999 ${symbol_pound} 这里配置 9999 的原因是，测试方便。
    end-code: 9999 ${symbol_pound} 这里配置 9999 的原因是，测试方便。

debug: false
